### ISSUE TITLE
how would you make this work for css module imports that dont have an extension?

### ISSUE THREAD

**Issue by faceyspacey** [ckknight/css-module-flow#1]
e.g:

```
import styles from '../css/foo'
```

where `foo` is the file `foo.css`.

**Comment by ckknight** [comment]
In https://flowtype.org/docs/advanced-configuration.html the `module.file_ext` configuration.

You'll probably still want to have `module.file_ext=.js` at least, but also `module.file_ext=.css`

**Comment by faceyspacey** [comment]
ah, I had to still have `module.file_ext=.js`. That solved it. thanks!
