### ISSUE TITLE
Does not work when node_modules is being ignored

### ISSUE THREAD

**Issue by vjpr** [ckknight/css-module-flow#2]
I couldn't get this to work when I am ignoring `node_modules` in `.flowconfig` just as an FYI.

I use the following which works. But I can't seem to access modules that are ignored.

```
module.name_mapper='.*\.css$' -> '<PROJECT_ROOT>/config/flow/css-modules-stub.js'
```

**Comment by ckknight** [comment]
You shouldn't be ignoring all of `node_modules` in `.flowconfig`.

**Comment by vjpr** [comment]
Too many errors otherwise from 3rd party typings (with invalid or outdated typings). Its an open issue and a common practice: https://github.com/facebook/flow/issues/869

**Comment by ckknight** [comment]
Then `css-module-flow` is not supported in that circumstance.

**Comment by FDiskas** [comment]
Can we some how to remove or skip ignoring this particular module? :cactus:
